server:
  port: 8080
spring:
  application:
    name: SpringData
  datasource:
    url: jdbc:h2:mem:spring_data_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;DATABASE_TO_UPPER=false;
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
logging:
  level:
    root: info
    org:
      springframework: info
      hibernate: info
      h2: info
    com.magicsoup: info